/* =========================================================================
   Copy & Share — plain-text reports and self-contained shareable links.

   The app is a static site with no result storage, so a shared link carries
   the whole analysis in its URL fragment: JSON → gzip → base64url. The
   fragment never leaves the browser (it isn't sent to the server), and the
   recipient's page rebuilds the board from it without a rescan.
   ========================================================================= */

import {
  POSSIBILITY_LABELS, DIFFICULTY_LABELS, EFFECTIVENESS_LABELS, IMPORTANCE_LABELS
} from './parser.js';

const SHARE_VERSION = 1;
const SHARE_PARAM = 'r';
// Browsers handle far longer URLs, but chat apps and mail clients start
// truncating well before this. Past the cap we copy the report text instead.
const MAX_SHARE_URL_CHARS = 8000;

/* ===== Plain-text report ===== */

function titleCase(value) {
  return String(value || '').replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}

function buildIssuesReport(data, rpMode) {
  const lines = [];
  lines.push(`LoopholeMap — ${data.title}`);
  lines.push(`Mode: ${rpMode ? 'CUSA / RP Law' : 'Real-World Law'}`);
  lines.push(`Overall risk: ${String(data.overallRisk).toUpperCase()} · ${data.nodes.length} issue${data.nodes.length === 1 ? '' : 's'}`);
  lines.push('');
  if (data.summary) {
    lines.push(data.summary);
    lines.push('');
  }
  lines.push('─'.repeat(56));
  lines.push('');

  data.nodes.forEach((n, i) => {
    lines.push(`${i + 1}. [${titleCase(n.type)}] ${n.title}`);
    if (n.section) lines.push(`   Section: ${n.section}`);
    lines.push(
      `   Severity: ${titleCase(n.severity)}` +
      ` · Possibility: ${POSSIBILITY_LABELS[n.possibility] || '—'}` +
      ` · Difficulty: ${DIFFICULTY_LABELS[n.difficulty] || '—'}` +
      ` · Effectiveness: ${EFFECTIVENESS_LABELS[n.effectiveness] || '—'}` +
      ` · Importance: ${IMPORTANCE_LABELS[n.importance] || '—'}`
    );
    if (n.description) lines.push(`   Issue: ${n.description}`);
    if (n.exploitation) lines.push(`   How it's exploited: ${n.exploitation}`);
    if (n.suggestedFix) lines.push(`   Suggested fix: ${n.suggestedFix}`);
    lines.push('');
  });

  if (data.filteredOwnershipTeamNodes > 0) {
    lines.push(`(${data.filteredOwnershipTeamNodes} Ownership Team-only finding${data.filteredOwnershipTeamNodes === 1 ? '' : 's'} excluded.)`);
    lines.push('');
  }

  lines.push('Generated by LoopholeMap');
  return lines.join('\n');
}

/* ===== Clipboard ===== */

async function copyText(text) {
  if (navigator.clipboard && window.isSecureContext) {
    try {
      await navigator.clipboard.writeText(text);
      return true;
    } catch {
      /* fall through to the legacy path below */
    }
  }

  // execCommand is deprecated but remains the only clipboard route on
  // insecure origins and older mobile browsers.
  const ta = document.createElement('textarea');
  ta.value = text;
  ta.setAttribute('readonly', '');
  ta.style.position = 'fixed';
  ta.style.top = '-1000px';
  ta.style.opacity = '0';
  document.body.appendChild(ta);
  ta.select();
  let ok = false;
  try { ok = document.execCommand('copy'); } catch { ok = false; }
  ta.remove();
  return ok;
}

/* ===== base64url <-> bytes ===== */

function bytesToBase64Url(bytes) {
  let binary = '';
  const CHUNK = 0x8000; // avoid blowing the argument limit on large payloads
  for (let i = 0; i < bytes.length; i += CHUNK) {
    binary += String.fromCharCode.apply(null, bytes.subarray(i, i + CHUNK));
  }
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

function base64UrlToBytes(text) {
  const binary = atob(text.replace(/-/g, '+').replace(/_/g, '/'));
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

async function pipeThrough(transform, bytes) {
  const stream = new Blob([bytes]).stream().pipeThrough(transform);
  return new Uint8Array(await new Response(stream).arrayBuffer());
}

/* ===== Share payload encode / decode ===== */

// Prefixes mark the encoding so a link made in a gzip-capable browser still
// decodes in one that lacks CompressionStream, and vice versa.
async function encodeSharePayload(data, rpMode) {
  const payload = { v: SHARE_VERSION, m: rpMode ? 'rp' : 'real', d: data };
  const bytes = new TextEncoder().encode(JSON.stringify(payload));

  if (typeof CompressionStream === 'function') {
    try {
      return 'g' + bytesToBase64Url(await pipeThrough(new CompressionStream('gzip'), bytes));
    } catch {
      /* fall back to the uncompressed form */
    }
  }
  return 'u' + bytesToBase64Url(bytes);
}

const TRUNCATED = 'That share link looks incomplete or damaged — ask for it again, unshortened.';

async function decodeSharePayload(token) {
  const flag = token[0];

  if (flag === 'g' && typeof DecompressionStream !== 'function') {
    throw new Error('This browser cannot open compressed share links.');
  }
  if (flag !== 'g' && flag !== 'u') {
    throw new Error('Unrecognized share link format.');
  }

  // Base64, gzip, and JSON errors all mean the same thing to the user: the
  // link arrived mangled (usually truncated by a chat app).
  let payload;
  try {
    let bytes = base64UrlToBytes(token.slice(1));
    if (flag === 'g') bytes = await pipeThrough(new DecompressionStream('gzip'), bytes);
    payload = JSON.parse(new TextDecoder().decode(bytes));
  } catch {
    throw new Error(TRUNCATED);
  }

  if (!payload || payload.v !== SHARE_VERSION || !payload.d || !Array.isArray(payload.d.nodes)) {
    throw new Error('This share link was made by a different version of LoopholeMap.');
  }
  return { data: payload.d, rpMode: payload.m !== 'real' };
}

async function buildShareUrl(data, rpMode) {
  const token = await encodeSharePayload(data, rpMode);
  const base = `${location.origin}${location.pathname}`;
  return `${base}#${SHARE_PARAM}=${token}`;
}

// Returns the token from the current URL fragment, or null.
function readShareToken() {
  const hash = location.hash.startsWith('#') ? location.hash.slice(1) : location.hash;
  if (!hash) return null;
  const match = new URLSearchParams(hash).get(SHARE_PARAM);
  return match || null;
}

function clearShareToken() {
  history.replaceState(null, '', `${location.pathname}${location.search}`);
}

export {
  buildIssuesReport, copyText,
  buildShareUrl, decodeSharePayload, readShareToken, clearShareToken,
  MAX_SHARE_URL_CHARS
};
